// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1LEmDD3owHl0gIvapN5MZIzj0SwsI5bg',
    appId: '1:390931350505:web:c5188fc0b6c7b5eaadc178',
    messagingSenderId: '390931350505',
    projectId: 'to-do-app-5ee20',
    authDomain: 'to-do-app-5ee20.firebaseapp.com',
    storageBucket: 'to-do-app-5ee20.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe-2UVJTkcZb9OLzbSPuF_DcGTXc8P6qo',
    appId: '1:390931350505:android:77a726c43b519423adc178',
    messagingSenderId: '390931350505',
    projectId: 'to-do-app-5ee20',
    storageBucket: 'to-do-app-5ee20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDShWAyg442xo5HzcvOvrr-2Bixl43NdS4',
    appId: '1:390931350505:ios:f074157f30119e95adc178',
    messagingSenderId: '390931350505',
    projectId: 'to-do-app-5ee20',
    storageBucket: 'to-do-app-5ee20.appspot.com',
    iosClientId: '390931350505-epn6dih50m8e3pr9h86g0feems9kkqcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDShWAyg442xo5HzcvOvrr-2Bixl43NdS4',
    appId: '1:390931350505:ios:f074157f30119e95adc178',
    messagingSenderId: '390931350505',
    projectId: 'to-do-app-5ee20',
    storageBucket: 'to-do-app-5ee20.appspot.com',
    iosClientId: '390931350505-epn6dih50m8e3pr9h86g0feems9kkqcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
